---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/webhookrelay/webhookrelay-operator

steps:
- name: test
  pull: default
  image: golang
  commands:
  - make test

- name: build
  pull: default
  image: golang
  commands:
  - make build

- name: lint-code
  pull: default
  image: golang
  commands:
  - make golangci-lint
  - make lint

- name: lint-charts
  pull: default
  image: quay.io/helmpack/chart-testing:v3.0.0-rc.1
  commands:
  - git remote add k8s https://github.com/webhookrelay/webhookrelay-operator
  - git fetch k8s master
  - ct lint --config .scripts/ct.yaml

- name: publish
  pull: default
  image: plugins/docker
  settings:
    auto_tag: true
    registry: quay.io
    repo: webhookrelay/webhookrelay-operator
    dockerfile: build/Dockerfile
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

