---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/webhookrelay/webhookrelay-operator

steps:
- name: test
  pull: golang:1.19
  image: golang
  commands:
  - make test

- name: build
  pull: default
  image: golang:1.19
  commands:
  - make build

- name: lint-code
  pull: default
  image: golang:1.19
  commands:
  - make golangci-lint
  - make lint

- name: lint-charts
  pull: default
  image: quay.io/helmpack/chart-testing:v3.0.0-rc.1
  commands:
  - git remote add k8s https://github.com/webhookrelay/webhookrelay-operator
  - git fetch k8s master
  - ct lint --config .scripts/ct.yaml
