---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/webhookrelay/webhookrelay-operator

steps:
- name: test
  pull: golang:1.17
  image: golang
  commands:
  - make test

- name: build
  pull: default
  image: golang:1.17
  commands:
  - make build

- name: lint-code
  pull: default
  image: golang:1.17
  commands:
  - make golangci-lint
  - make lint

- name: lint-charts
  pull: default
  image: quay.io/helmpack/chart-testing:v3.0.0-rc.1
  commands:
  - git remote add k8s https://github.com/webhookrelay/webhookrelay-operator
  - git fetch k8s master
  - ct lint --config .scripts/ct.yaml

- name: publish-multiarch-images
  image: golang:1.17
  commands:
    # Set the hosts
    - docker login --username "$${DOCKER_USERNAME}" --password "$${DOCKER_PASSWORD}"
    - docker buildx create --name cluster
    - DOCKER_HOST=$${DOCKER_ARM_BUILDER} docker buildx create --name cluster --append
    - docker buildx use cluster
    # Build the image
    - make buildx-images
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_ARM_BUILDER:
      from_secret: docker_arm_builder
  volumes:
    - name: dockersocket
      path: /var/run/docker.sock

# TODO: enable once OK
# trigger:
#   branch:
#   - master
#   ref:
#     include:
#     - refs/tags/**