name: image

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
      - uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: webhookrelay/webhookrelay-operator
      - env:
          auth_token: ${{ secrets.auth_token }}
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}" | ko login docker.io --username "${{ secrets.DOCKER_PASSWORD }}" --password-stdin
          make ko-build