name: image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: Image version to publish
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: "1.27.1"
      - uses: imjasonh/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10
        env:
          KO_DOCKER_REPO: webhookrelay/webhookrelay-operator
      - name: Build
        env:
          VERSION: ${{ github.event.release.tag_name || inputs.version }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | ko login docker.io --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          make ko-build VERSION="${VERSION}"
